-- liquibase formatted sql
-- changeset margo:1

CREATE TABLE Employees
(
  id bigint generated by default as identity,
  name varchar(255) NOT NULL,
  department varchar(255) NOT NULL,
  salary bigint NOT NULL,
  CONSTRAINT Employees_pkey PRIMARY KEY (id)
);

INSERT INTO employees (name, department, salary)
VALUES
('Maria', 'sales', 60000),
('Timothy', 'sales', 70000),
('Harry', 'IT', 150000),
('Alice', 'IT', 200000),
('Archie', 'accounting', 100000);

